package com.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "BankWebServiceDelegate", targetNamespace = "http://bankwebser.com/")
public interface BankWebServiceDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "setPayment", targetNamespace = "http://bankwebser.com/", className = "com.wsdl.SetPayment")
	@ResponseWrapper(localName = "setPaymentResponse", targetNamespace = "http://bankwebser.com/", className = "com.wsdl.SetPaymentResponse")
	public String setPayment(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "commonMet", targetNamespace = "http://bankwebser.com/", className = "com.wsdl.CommonMet")
	@ResponseWrapper(localName = "commonMetResponse", targetNamespace = "http://bankwebser.com/", className = "com.wsdl.CommonMetResponse")
	public String commonMet();

}
